'use client';

import React from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';

export type TopNavTab = 'pokemon' | 'locations' | 'moves' | 'generations';

const tabs: Array<{ key: TopNavTab; href: string; label: string }> = [
  { key: 'pokemon', href: '/pokemon', label: 'Pokemon' },
  { key: 'locations', href: '/locations', label: 'Locations' },
  { key: 'moves', href: '/moves', label: 'Moves' },
  { key: 'generations', href: '/generations', label: 'Generations' },
];

function activeFromPathname(pathname: string): TopNavTab {
  if (pathname.startsWith('/locations')) return 'locations';
  if (pathname.startsWith('/moves')) return 'moves';
  if (pathname.startsWith('/generations')) return 'generations';
  return 'pokemon';
}

export function TopNav({ activeTab }: { activeTab?: TopNavTab }) {
  const pathname = usePathname() || '/pokemon';
  const router = useRouter();
  const active = activeTab ?? activeFromPathname(pathname);

  return (
    <div className="w-full rounded-b-2xl bg-white dark:bg-zinc-900 shadow-lg dark:shadow-zinc-800/50 p-6">
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2 flex-shrink-0">
          <Link href="/pokemon" aria-label="Go to Pokemon list">
            <div className="w-14 h-14 rounded-lg overflow-hidden hover:opacity-80 transition-opacity">
              <img src="/favicon.ico" alt="Home" className="w-full h-full object-contain" />
            </div>
          </Link>

          <button
            type="button"
            aria-label="Back"
            onClick={() => {
              if (typeof window !== 'undefined' && window.history.length > 1) {
                router.back();
                return;
              }
              router.push('/pokemon');
            }}
            className="w-10 h-10 rounded-lg bg-zinc-200 dark:bg-zinc-800 hover:bg-zinc-300 dark:hover:bg-zinc-700 transition-colors flex items-center justify-center"
          >
            <svg
              viewBox="0 0 24 24"
              width="20"
              height="20"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="text-gray-700 dark:text-gray-300"
            >
              <path d="M15 18l-6-6 6-6" />
            </svg>
          </button>
        </div>

        <div className="flex-1 flex flex-col items-center justify-center gap-2">
          <h1 className="text-2xl font-semibold text-gray-800 dark:text-gray-200">Full Pokemon List</h1>
          <h2 className="text-sm text-gray-500 dark:text-gray-400">
            Generated by{' '}
            <a
              href="https://pokeapi.co/"
              className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300"
            >
              PokeAPI
            </a>
          </h2>
        </div>
      </div>

      <div className="mt-4 w-full max-w-4xl mx-auto">
        <div className="flex gap-2">
          {tabs.map((t) => {
            const isActive = t.key === active;
            return (
              <Link
                key={t.key}
                href={t.href}
                className={[
                  'flex-1 px-4 py-2 rounded-lg font-medium text-center transition-colors',
                  isActive
                    ? 'bg-blue-500 text-white'
                    : 'bg-zinc-200 dark:bg-zinc-800 text-gray-700 dark:text-gray-300 hover:bg-zinc-300 dark:hover:bg-zinc-700',
                ].join(' ')}
              >
                {t.label}
              </Link>
            );
          })}
        </div>
      </div>
    </div>
  );
}

