import Link from 'next/link';

export default function About() {
  return (
    <div className="flex min-h-screen flex-col bg-zinc-50 dark:bg-black">
      <div className="w-full rounded-b-2xl bg-white dark:bg-zinc-900 shadow-lg dark:shadow-zinc-800/50 p-6 flex items-center gap-4">
        <Link href="/" className="flex-shrink-0">
          <div className="w-12 h-12 rounded-lg overflow-hidden hover:opacity-80 transition-opacity">
            <img src="/favicon.ico" alt="Home" className="w-full h-full object-contain" />
          </div>
        </Link>
        <div className="flex-1 flex flex-col items-center justify-center gap-2">
          <h1 className="text-2xl font-semibold text-gray-800 dark:text-gray-200">Full Pokemon List</h1>
          <h2 className="text-sm text-gray-500 dark:text-gray-400">Generated by <a href="https://pokeapi.co/" className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300">PokeAPI</a></h2>
        </div>
      </div>
      <div className="flex flex-1 items-center justify-center p-4">
        <div className="w-full max-w-4xl rounded-2xl bg-white dark:bg-zinc-900 shadow-lg dark:shadow-zinc-800/50 p-6 flex flex-col items-center justify-center gap-4">
          <h1 className="text-2xl font-semibold text-gray-800 dark:text-gray-200">About</h1>
          <Link 
            href="/pokemon"
            className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300 underline"
          >
            Back to Full Pokemon List
          </Link>
        </div>
      </div>
    </div>
  );
}
