'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';

interface Pokemon {
  name: string;
  url: string;
}

interface PokemonListResponse {
  results: Pokemon[];
}

interface PokemonData {
  id: number;
  name: string;
  sprites: {
    front_default: string | null;
  };
  types: Array<{
    slot: number;
    type: {
      name: string;
      url: string;
    };
  }>;
}

function getPokemonId(url: string): number {
  const matches = url.match(/\/pokemon\/(\d+)\//);
  return matches ? parseInt(matches[1], 10) : 0;
}

function getPokemonSpriteUrl(id: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
}

function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function formatPokemonName(name: string): string {
  return name
    .split('-')
    .map((word) => capitalizeFirst(word))
    .join(' ');
}

function getTypeColor(typeName: string): string {
  const colors: Record<string, string> = {
    normal: '#A8A878',
    fire: '#F08030',
    water: '#6890F0',
    electric: '#F8D030',
    grass: '#78C850',
    ice: '#98D8D8',
    fighting: '#C03028',
    poison: '#A040A0',
    ground: '#E0C068',
    flying: '#A890F0',
    psychic: '#F85888',
    bug: '#A8B820',
    rock: '#B8A038',
    ghost: '#705898',
    dragon: '#7038F8',
    dark: '#705848',
    steel: '#B8B8D0',
    fairy: '#EE99AC',
  };
  return colors[typeName.toLowerCase()] || '#68A090';
}

export default function Home() {
  const [pokemonList, setPokemonList] = useState<PokemonData[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');

  // Load Pokemon progressively
  useEffect(() => {
    async function loadAllData() {
      const response = await fetch('https://pokeapi.co/api/v2/pokemon?limit=10000');
      const data: PokemonListResponse = await response.json();
      
      // Sort URLs by Pokemon ID for better progressive display
      const sortedUrls = data.results.sort((a, b) => {
        const idA = getPokemonId(a.url);
        const idB = getPokemonId(b.url);
        return idA - idB;
      });
      
      setLoading(false); // Allow interactivity as soon as we start loading
      
      // Load Pokemon progressively
      for (const pokemon of sortedUrls) {
        const pokemonResponse = await fetch(pokemon.url);
        const pokemonInfo: PokemonData = await pokemonResponse.json();
        
        // Add each Pokemon as it loads, maintaining sorted order
        setPokemonList((prev) => {
          const updated = [...prev, pokemonInfo];
          return updated.sort((a, b) => a.id - b.id);
        });
      }
    }

    loadAllData();
  }, []);

  if (loading) {
    return (
      <div className="flex min-h-screen flex-col bg-zinc-50 dark:bg-black">
        <div className="w-full rounded-b-2xl bg-white dark:bg-zinc-900 shadow-lg dark:shadow-zinc-800/50 p-6 flex flex-col items-center justify-center gap-2">
          <h1 className="text-2xl font-semibold text-gray-800 dark:text-gray-200">Full Pokemon List</h1>
          <h2 className="text-sm text-gray-500 dark:text-gray-400">Generated by <a href="https://pokeapi.co/" className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300">PokeAPI</a></h2>
        </div>
        <div className="flex flex-1 flex-col items-center justify-start p-4 pb-8 gap-4">
          <div className="w-full max-w-4xl">
            <input
              type="text"
              placeholder="Search Pokemon..."
              value=""
              disabled
              className="w-full px-4 py-3 rounded-2xl bg-white dark:bg-zinc-900 border-2 border-zinc-200 dark:border-zinc-800 text-gray-800 dark:text-gray-200 placeholder-gray-400 dark:placeholder-gray-500 opacity-50 cursor-not-allowed"
            />
          </div>
          <div className="w-full max-w-4xl h-[800px] rounded-2xl bg-white dark:bg-zinc-900 shadow-lg dark:shadow-zinc-800/50 p-6 flex items-center justify-center">
            <span className="text-gray-600 dark:text-gray-400">Loading Pokemon...</span>
          </div>
        </div>
        <div className="flex justify-center pb-6">
          <Link 
            href="/about"
            className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300 underline"
          >
            About
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen flex-col bg-zinc-50 dark:bg-black">
      <div className="w-full rounded-b-2xl bg-white dark:bg-zinc-900 shadow-lg dark:shadow-zinc-800/50 p-6 flex flex-col items-center justify-center gap-2">
        <h1 className="text-2xl font-semibold text-gray-800 dark:text-gray-200">Full Pokemon List</h1>
        <h2 className="text-sm text-gray-500 dark:text-gray-400">Generated by <a href="https://pokeapi.co/" className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300">PokeAPI</a></h2>
      </div>
      <div className="flex flex-1 flex-col items-center justify-start p-4 pb-8 gap-4">
        <div className="w-full max-w-4xl">
          <input
            type="text"
            placeholder="Search Pokemon..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full px-4 py-3 rounded-2xl bg-white dark:bg-zinc-900 border-2 border-zinc-200 dark:border-zinc-800 text-gray-800 dark:text-gray-200 placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:border-blue-500 dark:focus:border-blue-400 transition-colors"
          />
        </div>
        <div className="w-full max-w-4xl h-[800px] rounded-2xl bg-white dark:bg-zinc-900 shadow-lg dark:shadow-zinc-800/50 p-6 flex flex-col">
          <div className="overflow-y-auto flex-1">
            <ul className="grid grid-cols-3 gap-4">
              {pokemonList
                .filter((pokemon) => {
                  if (!searchTerm) return true;
                  const search = searchTerm.toLowerCase();
                  const pokemonName = pokemon.name.toLowerCase();
                  return pokemonName.includes(search) || pokemon.id.toString().includes(search);
                })
                .map((pokemon) => {
                  const types = pokemon.types.sort((a, b) => a.slot - b.slot);
                  const type1 = types[0]?.type.name;
                  const type2 = types[1]?.type.name;
                  const type1Color = type1 ? getTypeColor(type1) : '';
                  const type2Color = type2 ? getTypeColor(type2) : '';
                  
                  const borderStyle: React.CSSProperties = {};
                  if (type1Color) {
                    borderStyle.borderLeftWidth = '10px';
                    borderStyle.borderLeftColor = type1Color;
                  }
                  if (type2Color) {
                    borderStyle.borderRightWidth = '10px';
                    borderStyle.borderRightColor = type2Color;
                  }
                  
                  return (
                    <li
                      key={pokemon.name}
                      className="flex flex-col items-center gap-2 p-3 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors relative"
                      style={borderStyle}
                    >
                      <span className="text-sm text-gray-400 dark:text-gray-500 font-mono">
                        #{pokemon.id}
                      </span>
                      <img
                        src={pokemon.sprites.front_default || getPokemonSpriteUrl(pokemon.id)}
                        alt={pokemon.name}
                        className="w-16 h-16 object-contain"
                      />
                      <span className="text-sm text-center text-gray-800 dark:text-gray-200">
                        {formatPokemonName(pokemon.name)}
                      </span>
                    </li>
                  );
                })}
            </ul>
          </div>
        </div>
      </div>
      <div className="flex justify-center pb-6">
        <Link 
          href="/about"
          className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300 underline"
        >
          About
        </Link>
      </div>
    </div>
  );
}
